#+TITLE: Lab 3 - Linked Lists

You will write a program to process the lines in a text file using a linked list ADT and raw pointers.

* Node class

You will create a class “Node” with the following private data attributes:
- =line= – line from a file (string)
- =next= - (pointer to a Node)

Put your class definition in a header file and the implementation of the methods in a =.cpp= file.

Follow the style they use in the book of having a =#include= for the implementation file at the bottom of the header file.

You will have the following public methods:
- Accessors and mutators for each attribute
- Constructor that initializes the attributes to nulls (empty string and =nullptr=)

* LinkedList class

You will create a class “LinkedList” with the following private data attributes:
- =headPtr= – raw pointer to the head of the list
- =numItems= – number of items in the list

Put your class definition in a header file and the implementation of the methods in a =.cpp= file.

Follow the style they use in the book of having a =#include= for the implementation file at the bottom of the header file.

You will have the following public methods:
- Accessor to get the current size (=numItems=)
- Constructor that initializes numItems to zero and =headPtr= to =nullptr=
- Add a =node= – this method will take as input one string value. It will then create a node object and set the attribute. Then it will put it in the linked list at the correct position – ascending order – avoiding duplicates. You will do all of the work while building the linked list.
- =toVector= – returns vector with the contents of the list. You will use only the =push_back= method to get the strings into the vector.

* Client program

Your program will ask the user for the file name, open the text file, read each line and invoke the addNode method.  Make sure the file opened correctly before you start processing it. You do not know how many lines are in the file so your program should read until it gets to the end of the file.

It will display the contents of the list (the lines that were read from the file in sorted order with no duplicates) using the =LinkedList= class method =toVector= that puts all of the lines into a vector and returns it to the program that will display it.

Your client program will do the following:
- Read file name from user
- Display the number of lines that were read out of the file and were passed to the =addNode= method.
- Display the lines in your linked list using the class method =toVector= to get the lines.
- Display the number of lines in the vector.
- I have attached three files you can use to test your program. Blackboard handles files in a strange way sometimes. You may not be able to directly download the files, but you can open them, copy and paste the contents into a notepad file and save that file.
- You will write all of the code for processing the linked list - do not use any predefined objects in C++.  You do not need to offer a user interface – simply display the number of lines read from the file, the list using the =toVector= method and the number of lines in the vector.

You will submit the following:
- All of program source and header files compressed into a zip file.
- Name your zip file ~lab3_Firstname_Lastname~. You decide what to name the other files.

* Sample Data

#+name: stuff-one
#+begin_src text :tangle ./stuff1.txt
The sky is blue.
Clovis Bagwell
Shake rattle and roll.
The quick brown fox jumped over the lazy dog.
One red bean stuck in the bottom of a tin bowl.
Rats live on no evil star.
The sky is blue.
Mark Knopfler
The sky is blue.
Archibald Beechcroft
Oliver Crangle
Workers of the world unite.
Oliver Crangle
A squid eating dough in a polyethylene bag is fast and bulbous.
Somerset Frisby
Mark Knopfler
Oliver Crangle
Data structures is really hard.
It's raining and boring outside.
It's raining and boring outside.
It's raining and boring outside.
Somerset Frisby
Henry Bemis
Mark Knopfler
#+end_src

#+name: stuff-two
#+begin_src text :tangle ./stuff2.txt
The sky is blue.
Clovis Bagwell
Shake rattle and roll.
The quick brown fox jumped over the lazy dog.
One red bean stuck in the bottom of a tin bowl.
Rats live on no evil star.
The sky is blue.
Mark Knopfler
The sky is blue.
Archibald Beechcroft
Oliver Crangle
Workers of the world unite.
Oliver Crangle
Somerset Frisby
Mark Knopfler
Oliver Crangle
Somerset Frisby
Henry Bemis
Mark Knopfler
Data structures is really hard.
A squid eating dough in a polyethylene bag is fast and bulbous.
A squid eating dough in a polyethylene bag is fast and bulbous.
A squid eating dough in a polyethylene bag is fast and bulbous.
A squid eating dough in a polyethylene bag is fast and bulbous.
Somerset Frisby
Henry Bemis
Mark Knopfler
Romney Wordsworth
#+end_src

#+name: stuff-three
#+begin_src text :tangle ./stuff3.txt
A squid eating dough in a polyethylene bag is fast and bulbous.
A squid eating dough in a polyethylene bag is fast and bulbous.
A squid eating dough in a polyethylene bag is fast and bulbous.
A squid eating dough in a polyethylene bag is fast and bulbous.
The sky is blue.
Clovis Bagwell
Shake rattle and roll.
The quick brown fox jumped over the lazy dog.
One red bean stuck in the bottom of a tin bowl.
Rats live on no evil star.
The sky is blue.
Mark Knopfler
The sky is blue.
Archibald Beechcroft
Oliver Crangle
Workers of the world unite.
Oliver Crangle
Somerset Frisby
A squid eating dough in a polyethylene bag is fast and bulbous.
Mark Knopfler
Oliver Crangle
Somerset Frisby
Henry Bemis
Mark Knopfler
Data structures is really hard.
It's raining and boring outside.
It's raining and boring outside.
It's raining and boring outside.
Somerset Frisby
Henry Bemis
Mark Knopfler
One red bean stuck in the bottom of a tin bowl.
One red bean stuck in the bottom of a tin bowl.
One red bean stuck in the bottom of a tin bowl.
#+end_src

* Lab Grade Points

Labs will be graded on the following:
- Comments - Including:
  + Program description (comment block at top of program)
  + Function descriptions for every function other than =main()= (see function heading below)
  + Comments at major algorithm steps (at a minimum)
- Followed directions
- Correct output
- Structured program design
- Meaningful identifier names

* NOTES

The “NEVER DO THIS” list of rules:
- You will NEVER use break, exit, return, pass, continue or anything to leave a loop (or iteration), function, or other construct prematurely, unless it is part of the structure as in a case statement.
- You will NEVER have a function call itself, unless it is intentional recursion.
- You will NEVER use global variables.  However, you may use global constants if it is appropriate and they are used properly.
- You will have only one return statement in a function. (Exception – Multiple return statements may be necessary in a recursive function.)
