#+TITLE: Problem 4: Box of Bricks

[LINK HERE TO PDF OF PROBLEM]

* Contents :toc:
- [[#info][Info]]
- [[#c][C++]]

* Info

Little Bob likes playing with his box of bricks. 
He puts the bricks one upon another and builds stacks of different height. 
"Look, I've built a wall!", he tells his older sister Alice. 
"Nah, you should make all stacks the same height.  Then you would have a real wall.", she retorts. 
After a little consideration, Bob sees that she is right. So he sets out to rearrange the bricks, one by one, such that all stacks are the same height
afterwards. 
But since Bob is lazy he wants to do this with the minimum number of bricks moved. Can you help?

/Input Specification:/
- The input consists of several data sets. 
- Each set begins with a line containing the number n of stacks Bob has built. 
- The next line contains n numbers, which are the heights hi of the n stacks. 
- You may assume 1 ≤ n ≤ 50 and 1 ≤ hi ≤ 100. 
- The total number of bricks will be divisible by the number of stacks. 
- Thus, it is always possible to rearrange the bricks such that all stacks have the same height. 
- The input is terminated by a set starting with n = 0, which should not be processed.

/Output Specification:/
- For each set, first print the number of the set, as shown in the sample output. 
- Then print the line "The minimum number of moves is k.", where k is the minimum number of bricks that have to be moved in
order to make all the stacks the same height. 
- Output a blank line after each set.

/Sample Input and Output:/

#+BEGIN_SRC 
6
5 2 4 1 7 5
0
#+END_SRC

#+BEGIN_SRC 
Set #1
The minimum number of moves is 5.
#+END_SRC

* C++

#+BEGIN_SRC C++
#include <iostream>
#include <iomanip>
#include <vector>
#include <string>

int main()
{
    int numStacks = 0;
    std::cin >> numStacks;

    std::vector<int> movesPerStack;

    while (numStacks != 0)
    {
        int* stacks = new int[numStacks];

        int stackHeight = 0;
        int totalHeight = 0;

        for (int i = 0; i < numStacks; ++i)
        {
            std::cin >> stacks[i];
            totalHeight += stacks[i];
        }

        int targetHeight = totalHeight / numStacks;
        
        int moves = 0;
        for (int i = 0; i < numStacks; ++i)
        {
            if (stacks[i] > targetHeight)
            {
                moves += stacks[i] - targetHeight;
            }
        }

        delete[] stacks;

        movesPerStack.push_back(moves);

        std::cin >> numStacks;
    }

    int stackNumber = 1;
    for (int move : movesPerStack)
    {
        std::cout << "Set #" << stackNumber++ << '\n'
                  << "The minimum number of moves is " << move  << '.' << '\n' << std::endl;
    }

    return 0;
}
#+END_SRC