#+title: 0.8 Problems

* Python comprehension problems

For each of the following problems, write the one-line procedure using a comprehension.

** Problem 0.8.1: increments(L)

input: list L of numbers.
output: list of numbers in which the ith element is one plus the ith element of L.

Example: increments([1,5,7]) should return [2,6,8].

** Problem 0.8.2: cubes(L)

input: list L of numbers.
output: list of numbers in which the ith element is the cube of the ith element of L.

Example: given [1, 2, 3] return [1, 8, 27].

** Problem 0.8.3: tuple sum(A, B)

input: lists A and B of the same length, where each element in each list is a pair (x, y) of numbers.
output: list of pairs (x, y) in which the first element of the ith pair is the sum of the first element of the ith pair in A and the first element of the ith pair in B.

example: given lists [(1, 2), (10, 20)] and [(3, 4), (30, 40)], return [(4, 6), (40, 60)].

** Problem 0.8.4: inv dict(d)

input: dictionary d representing an invertible function f
output: dictionary representing the inverse of f, the returned dictionary’s keys are the values of d and its values are the keys of d

example: given an English-French dictionary

{'thank you': 'merci', 'goodbye': 'au revoir'}
return a French-English dictionary
{'merci':'thank you', 'au revoir':'goodbye'}

** Problem 0.8.5

First write a procedure row(p, n) with the following spec:

input: integer p, integer n
output: n-element list such that element i is p + i

example: given p = 10 and n = 4, return [10, 11, 12, 13]

Next write a comprehension whose value is a 15-element list of 20-element lists such that the j th element of the ith list is i + j. You can use row(p, n) in your comprehension.

Finally, write the same comprehension but without using row(p, n). Hint: replace the call to row(p, n) with the comprehension that forms the body of row(p, n).

* Functional inverse
** Problem 0.8.6

Is the following function invertible? If yes, explain why.

If not, can you change domain and/or codomain of the function to make it invertible? Provide the drawing.

** Problem 0.8.7

Is the following function invertible? If yes, explain why.

If not, can you change domain and/or codomain of the function to make it invertible? Provide the drawing.

* Functional composition
** Problem 0.8.8

Let f : R → R where f (x) = √abs(x).

Is there a choice of domain and codomain for the function g(x) with rule g(x) = x such that g ◦ f is defined?

If so, specify it. If not, explain why not. Could you change domain and/or codomain of f or g so that g ◦ f will be defined?

** Problem 0.8.9

Consider functions f and g in the following figure:

Is f ◦ g defined? If so, draw it, otherwise explain why not.

* Probability
** Problem 0.8.10

A function f (x) = x+1 with domain {1, 2, 3, 5, 6} and codomain {2, 3, 4, 6, 7} has the following probability function on its domain:

Pr(1) = 0.5, Pr(2) = 0.2 and Pr(3) = Pr(5) = Pr(6) = 0.1.

What is the probability of getting an even number as an output of f (x)?

An odd number?

** Problem 0.8.11

A function g(x) = x mod 3 with domain {1, 2, 3, 4, 5, 6, 7} and codomain {0, 1, 2} has the following probability function on its domain:

Pr(1) = Pr(2) = Pr(3) = 0.2 and Pr(4) = Pr(5) = Pr(6) = Pr(7) = 0.1.

What is the probability of getting 1 as an output of g(x)?

What is the probability of getting 0 or 2?
