#+title: Lab 0.5 - Introduction to Python

* Task 0.5.1

Use Python to find the number of minutes in a week.

#+begin_src python :session
60 * 24 * 7
#+end_src

#+RESULTS:
: 10080

* Task 0.5.2

Find the remainder of 2304811 divided by 47 without using the modulo operator, %.

#+begin_src python :session
2304811 - ((2304811 // 47) * 47)
#+end_src

#+RESULTS:
: 25

* Task 0.5.3

Enter a Boolean expression to test whether the sum of 673 and 909 is divisible by 3.

#+begin_src python :session
(673 + 909) % 3 == 0
#+end_src

#+RESULTS:
: False

* Task 0.5.4

Assign the value -9 to x and 1/2 to y.

Predict the value of the following expression, then enter it to check your prediction:

#+begin_src python
2**(y+1/2) if x+10<0 else 2**(y-1/2)
#+end_src

#+begin_src python :session
x = -9
y = 1/2

2**(y+1/2) if x+10<0 else 2**(y-1/2)
#+end_src

#+RESULTS:
: 1.0

* Task 0.5.5

Write a comprehension over ={1, 2, 3, 4, 5}= whose value is the set consisting of the squares of the first five positive integers.

#+begin_src python :session
{x*x for x in {1,2,3,4,5}}
#+end_src

#+RESULTS:
: {1, 4, 9, 16, 25}

* Task 0.5.6

Write a comprehension over {0, 1, 2, 3, 4} whose value is the set consisting of the first five powers of two, starting with 20.

#+begin_src python :session
{2**x for x in {0,1,2,3,4}}
#+end_src

#+RESULTS:
: {1, 2, 4, 8, 16}

* Task 0.5.7

The value of the previous comprehension,

#+begin_src python :session
len({x*y for x in {1,2,3} for y in {2,3,4}})
#+end_src

#+RESULTS:
: 7

is a seven-element set. 

Replace {1,2,3} and {2,3,4} with two other three-elements sets so that the value becomes a nine-element set.

#+begin_src python :session
len({x*y for x in {1,2,10} for y in {1,3,4}})

#+end_src

#+RESULTS:
: 9

* Task 0.5.8

Replace the same comprehension from Task 0.5.7 with two disjoint three-element sets so that the value becomes a five-element set.

#+begin_src python :session
len({x*y for x in {0,-3,1} for y in {-1,3,-9}})
#+end_src

#+RESULTS:
: 5
